#!/bin/bash

## train

# python3 src/tests/main_cheetah.py "train" \
# -n="simple_cheetah_symmetry" --use_sym_policy

# python3 src/tests/main_cheetah.py "train" \
# -n="simple_cheetah_custom" 

python3 src/tests/main_cheetah.py "train" \
-n="simple_cheetah_symmetry_oneway_noangle" --use_sym_policy

## test
# python3 src/tests/main_cheetah.py "test" \
# -n="simple_cheetah_symmetry_oneway" --use_sym_policy \
# -mp="models/simple_cheetah_symmetry_oneway/PPO_7700000.zip"

# "test" -n="simple_cheetah_symmetry_oneway" --use_sym_policy -mp="models/simple_cheetah_symmetry_oneway/PPO_7700000.zip"

